### ISSUE TITLE
Autocompletion doesn't work for generated files

### ISSUE THREAD

**Issue by rlidwka** [godot-rust/gdextension#40]
In the absence of documentation, the best way to figure things out is IDE autocompletion. Sadly, for generated files it doesn't work (at least in vscode on windows).

I've opened the issue here, please check it out:

https://github.com/rust-lang/rust-analyzer/issues/13711

Long story short, generated files are located in a different package from where they are included (`godot-codegen` vs `godot-core`). And that makes them invisible as far as autocompletion is concerned.

Not sure if it's intentional or not on the part of `rust-analyzer`, so opening an issue on both places.

**Comment by rlidwka** [comment]
In case you don't have VSCode, this is what I have by default:

![image](https://user-images.githubusercontent.com/999113/205409477-1e1c033f-cd71-4492-a0fe-d567d325fb1e.png)

And this is what happens if I move `/target/godot-gen` anywhere inside of `godot-core` module:

![image](https://user-images.githubusercontent.com/999113/205408793-e17dff65-989b-408b-8ac4-950ec332dc8b.png)

**Comment by Bromeon** [comment]
This problem is also present on CLion, and I agree we should do something about it. Good that we have this issue now 🙂 

The location where code is generated is indeed rather hacky at the moment. The problem is that not one, but _two_ crates need code generation:
* `godot-ffi` for low level "sys" symbols
* `godot-core` for classes, utility functions, enums etc.

I could let both directly depend on `godot-codegen`, however that would mean that some effort is duplicated (notably parsing the JSON file and caching some symbols). This may not be such a big issue however.

An alternative would be to split generated classes into their own crate (like it's done with `gdnative`), which might also help compile times. `godot-core` could then depend on that crate. The problem here is that there are quite a few bidirectional dependencies (e.g. classes use `Gd`, but `Gd` also needs to know about `Object` and `RefCounted` classes). It's likely possible to detangle this through certain abstractions, but it might be a bit of effort. I'm also a bit scared of silly orphan-rule limitations if trait implementations need to be split across crates.
