### ISSUE TITLE
Everything is successful unless version number screws up

### ISSUE THREAD

**Issue by Coder2195Text** [godot-rust/gdextension#47]
```
  --- stderr
  Build selected for Linux/Windows.
  thread 'main' panicked at 'failed to parse Godot version '4.0.beta8.mono.official.45cac42c0
  ': Regex capture failed', /home/coder2195/.cargo/git/checkouts/gdextension-25c68fb170a9fb9d/eaefd45/godot-codegen/src/godot_exe.rs:87:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ```

**Comment by RealAstolfo** [comment]
similar issue with me,
`  Found 'godot4' executable in PATH: /usr/bin/godot4
  cargo:rerun-if-changed=/usr/bin/godot4
  Godot version: 4.0.beta8.gentoo.45cac42c0


  --- stderr
  Build selected for Linux/Windows.
  thread 'main' panicked at 'failed to parse Godot version '4.0.beta8.gentoo.45cac42c0
  ': Regex capture failed', /home/dots/.cargo/git/checkouts/gdextension-25c68fb170a9fb9d/eaefd45/godot-codegen/src/godot_exe.rs:87:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by RealAstolfo** [comment]
`   Compiling godot-core v0.1.0 (https://github.com/godot-rust/gdextension?branch=master#5513c001)
   Compiling bindgen v0.63.0
error: failed to run custom build command for `godot-core v0.1.0 (https://github.com/godot-rust/gdextension?branch=master#5513c001)`

Caused by:
  process didn't exit successfully: `/home/dots/Documents/Projects/Exorium-Godot/target/debug/build/godot-core-c8db86b873c89a88/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=/home/dots/.cargo/git/checkouts/gdextension-25c68fb170a9fb9d/5513c00/godot-codegen/input/gen/extension_api.json
  Found 'godot4' executable in PATH: /usr/bin/godot4
  cargo:rerun-if-changed=/usr/bin/godot4
  Godot version: 4.0.beta8.gentoo.45cac42c0


  --- stderr
  thread 'main' panicked at 'failed to parse Godot version '4.0.beta8.gentoo.45cac42c0
  ': Version substring cannot be parsed: `4.0.beta8.gentoo.45cac42c0
  `', /home/dots/.cargo/git/checkouts/gdextension-25c68fb170a9fb9d/5513c00/godot-codegen/src/godot_exe.rs:87:13
`

problem still exists for gentoo builds

**Comment by Bromeon** [comment]
@RealAstolfo thanks for the heads-up, I'll look deeper into how this version looks exactly 👍
