### ISSUE TITLE
Generated code depends on functions only available under feature `convenience`

### ISSUE THREAD

**Issue by chitoyuu** [godot-rust/gdextension#60]
Screenshot from hapenia on Discord:

![](https://cdn.discordapp.com/attachments/940237853999386654/1061561680204664832/image.png)

**Comment by Bromeon** [comment]
Thanks! I think if we want to keep using that feature, we should probably run tests with and without it in CI.

**Comment by Bromeon** [comment]
Originally the intention of `convenience` (possibly to be renamed as `yolo` 😀) was that someone who wants to be aware of fallible operations can disable that feature and the number of panicking functions will be drastically reduced.

That said, I'm not sure if there are people truly wishing for that or if it's something we want to encourage as a best practice, as it has two notable downsides:
* Verbosity of code that never fails due to _external invariants_.
   * E.g. scene tree has a certain structure, so getting a node of a given name/type _must_ succeed or it's a bug.
   * If I know the value on GDScript side fits into a `u8`, then `to_variant()` _must_ succeed or it's a bug.
* Worse error messages. 
   * People tend to use `unwrap()` or `expect("literal")`, which lacks context information.
   * `get_node_as::<T>("path")` on the other hand can include a precise panic message, e.g. "there is a node at path `path` with type `U`, but type `T` was requested".

Maybe I'll remove this feature but keep the commented-out `#[cfg]` statements around in case we want to re-introduce it later. Keeping it may add quite some maintenance overhead which is probably not justifiable at this stage of the library.
